export enum NodeType {
  ScalarDeclaration = "ScalarDeclaration",
  StringDeclaration = "StringDeclaration",
  VectorDeclaration = "VectorDeclaration",
  ComputeVectorDeclaration = "ComputeVectorDeclaration",
  MatrixDeclaration = "MatrixDeclaration",
  ComputeMatrixDeclaration = "ComputeMatrixDeclaration",
  VectorRef = "VectorRef",
  MatrixRef = "MatrixRef",
  ScalarRef = "ScalarRef",
  ResultRef = "ResultRef",
  Scalar = "Scalar",
  VectorOperation = "VectorOperation",
  MatrixOperation = "MatrixOperation",
  FunctionDeclaration = "FunctionDeclaration",
  FunctionCall = "FunctionCall",
  Return = "Return",
  ArgRef = "ArgRef",
  PrintBlock = "PrintBlock",
  MethodOperation = "MethodOperation",
}
