const Spec = {
  comment: /#.*?$/,
  keyword: [
    "vector",
    "scaler",
    "matrix",
    "if",
    "else",
    "loop",
    "function",
    "return",
    "computeVector",
    "computeMatrix",
    "calcMat",
    "calcVec",
    "result",
    "print",
    "calc",
  ],
  ws: /[ \t]+/,
  arg: /arg\([a-zA-Z_][a-zA-Z0-9_]*,[a-zA-Z_][a-zA-Z0-9_]*\)/,
  number: /(?:[0-9]*\.[0-9]+|[0-9]+)(?:[eE][+-]?[0-9]+)?/,
  string: /"(?:\\["\\]|[^\n"\\])*"/,
  lp: "(",
  rp: ")",
  lb: "{",
  rb: "}",
  lbk: "[",
  rbk: "]",
  comma: ",",
  colon: ":",
  cross: "x",
  arrow: "->",
  assign: "=",
  plus: "+",
  minus: "-",
  times: "*",
  divide: "/",
  pow: "^",
  identifier: /[a-zA-Z_][a-zA-Z0-9_]*/,
  comparison: /==|!=|<=|>=|<|>/,
  nl: { match: /\n/, lineBreaks: true },
  print: /print\([a-zA-Z_][a-zA-Z0-9_]*,[a-zA-Z_][a-zA-Z0-9_]*\)/,
};

export default Spec;
