name: Build Binary & Publish Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: actions/upload-artifact@v2
        with:
          name: bin
          path: bin
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref_name }}
          release_name: matz@v${{ github.ref_name }}
          body: |
            Changes in this release:
            - Add feature A
            - Fix bug B
          draft: false
          prerelease: false
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: bin
      - run: zip -r bin.zip bin
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin.zip
          asset_name: bin.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
