name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p -e 'require("./package.json").version')"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "matz@v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
